### ISSUE TITLE
Abort in listening a contract tx

### ISSUE THREAD

**Issue by immartian** [Musicoin/orbiter#5]
Listen.js would abort with the follow breakpoint: 

 Internal tx: {"jsonrpc":"2.0","result":[{"action":{"callType":"call","from":"0xb560530ea7939a88093123af648f718f15e540cc","gas":"0xd9f8","input":"0x6049a45d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000180000000000000000000000000000000000000000000000000000000000000000344616e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d53386e34524b61744577745559356273754e6259385436514c47764156766a76663232733453753352394e5600000000000000000000000000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d5139336f52577338426f61684658734d6f4c347a346961424b62737a686e5359547977634a55524b46526a5400000000000000000000000000000000000000000000000000000000000000000000000000000000000035697066733a2f2f516d4e77667a737359544c4a646452415351503637344177446356544d647258334a39727763386351554d7a4c550000000000000000000000","to":"0x0697fdc2a44ec94fd9532711d1759dbf8effe55b","value":"0x0"},"blockHash":"0x26096674f6f4a21ce60987942660ab3aa1ad32a85603454a1e1c4c1bcc2be3b7","blockNumber":12947,"error":"Out of gas","subtraces":0,"traceAddress":[],"transactionHash":"0x1a71ef0f7d4c86548d92f388042caf1139aa50071666aa3701e46c96da7a13ca","transactionPosition":0,"type":"call"},{"action":{"callType":"call","from":"0x15b64d20202475b2ef8c8544e743f36eafe7507c","gas":"0x10d88","input":"0x","to":"0x008d4c913ca41f1f8d73b43d8fa536da423f1fb4","value":"0x4563918244f40000"},"blockHash":"0x26096674f6f4a21ce60987942660ab3aa1ad32a85603454a1e1c4c1bcc2be3b7","blockNumber":12947,"result":{"gasUsed":"0x0","output":"0x"},"subtraces":0,"traceAddress":[],"transactionHash":"0x8c36ac228ec3503878bd329bc11551bf2a70b4067322b8311d134fb855e877b7","transactionPosition":1,"type":"call"}],"id":12947}

/home/im/lab/musicoin/orbiter/tools/listen.js:122
            if (j.result.call)
                        ^

TypeError: Cannot read property 'call' of undefined
    at IncomingMessage.<anonymous> (/home/im/lab/musicoin/orbiter/tools/listen.js:122:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Although it seems didn't affect orbiter in remote(protected by `forever` process), it's a potential data integrity issue.

**Comment by immartian** [comment]
Adding try{ ... } to handle this issue but didn't get full understanding when this field, j.result.call, could be null. Closed for now as exception has been dealt with in a band-aid way.
